version: '3'
services:
  api:
    build: .
    ports:
    - "8000:80"
    volumes:
    - ./src/:/var/www/app/
    links:
    - db
    command: php artisan seed && /var/www/entrypoint.sh
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secur3r00tPassw0rd
      MYSQL_DATABASE: api
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: secur3Passw0rd
